{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.agoraio-usecase.common",
    "module": "rte",
    "version": "1.0.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "dtaotew47jhpvlzdz5pm5mwgxi"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rte-1.0.0-alpha.aar",
          "url": "rte-1.0.0-alpha.aar",
          "size": 326974,
          "sha512": "9f16b4a826215d7c5a8edbd6248e0c0991b9d23b77362a1cb5f3e7d98505785839ccf9043a3c7b5027ad7944a6b933a5e40f99efd926a362afd1aa5ad626047d",
          "sha256": "06e7b33362ba3d371c6a0dbba60ff84e4f28222be6bc92de22256cb68fb9de8b",
          "sha1": "06abd16082b882d6f30263815172fa6a6717d7b4",
          "md5": "62a674c5dcb39f886333c0180f5aa312"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.aliyun.dpa",
          "module": "oss-android-sdk",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "com.github.AgoraIO-Usecase",
          "module": "Tools",
          "version": {
            "requires": "log_java_1.0.4"
          }
        },
        {
          "group": "io.agora.rtc",
          "module": "full-sdk",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.agora.rtm",
          "module": "rtm-sdk",
          "version": {
            "requires": "1.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "rte-1.0.0-alpha.aar",
          "url": "rte-1.0.0-alpha.aar",
          "size": 326974,
          "sha512": "9f16b4a826215d7c5a8edbd6248e0c0991b9d23b77362a1cb5f3e7d98505785839ccf9043a3c7b5027ad7944a6b933a5e40f99efd926a362afd1aa5ad626047d",
          "sha256": "06e7b33362ba3d371c6a0dbba60ff84e4f28222be6bc92de22256cb68fb9de8b",
          "sha1": "06abd16082b882d6f30263815172fa6a6717d7b4",
          "md5": "62a674c5dcb39f886333c0180f5aa312"
        }
      ]
    }
  ]
}
