{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.agoraio-usecase.common",
    "module": "rte",
    "version": "1.0.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "ffmc53f6rbfllemcrhvmuy2ve4"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rte-1.0.0-alpha.aar",
          "url": "rte-1.0.0-alpha.aar",
          "size": 327091,
          "sha512": "a9b2fbdecddffb99defc650c1e10206c4eb855830c73f1415307f7c05552fc62ac8f3ae7db8d048e88f8dd626ba0a900891d225283b27ae1564da4844038009d",
          "sha256": "e73ead66c594ef1e5cc548a9fb813c3a3ca21023d61f449b0f2241cfd4947a31",
          "sha1": "63ad198e111afd0808d758b6a743583adcb63f0d",
          "md5": "7a59349ead53f974b88e19d07adc50d3"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.aliyun.dpa",
          "module": "oss-android-sdk",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "com.github.AgoraIO-Usecase",
          "module": "Tools",
          "version": {
            "requires": "log_java_1.0.4"
          }
        },
        {
          "group": "io.agora.rtc",
          "module": "full-sdk",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.agora.rtm",
          "module": "rtm-sdk",
          "version": {
            "requires": "1.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "rte-1.0.0-alpha.aar",
          "url": "rte-1.0.0-alpha.aar",
          "size": 327091,
          "sha512": "a9b2fbdecddffb99defc650c1e10206c4eb855830c73f1415307f7c05552fc62ac8f3ae7db8d048e88f8dd626ba0a900891d225283b27ae1564da4844038009d",
          "sha256": "e73ead66c594ef1e5cc548a9fb813c3a3ca21023d61f449b0f2241cfd4947a31",
          "sha1": "63ad198e111afd0808d758b6a743583adcb63f0d",
          "md5": "7a59349ead53f974b88e19d07adc50d3"
        }
      ]
    }
  ]
}
